In [7]:
import numpy as np 
from scipy import linalg

# Linear Algebra

The scipy.linalg() provides fas , stable & feature rich linear algebra routines . This module is build on top of optimized lib .

In [10]:
# The numpy matrix
mat1 = np.array([[1,2,] , [5,6]])
print(mat1)

mat2 = np.array([[56,9,8,4] , [5,6,7,8]])
print(mat2)


[[1 2]
 [5 6]]
[[56  9  8  4]
 [ 5  6  7  8]]


# Basic Matrix Operations

In [12]:
print(f"The inverse of mat is {linalg.inv(mat1)}")
print(f"The determinant of mat is {linalg.det(mat1)}")
print(f"The trace of mat is {np.trace(mat1)}")              # numpy, not linalg
print(f"The vector norm of mat is {linalg.norm(mat1)}")
print(f"The pseudo inverse of mat is {linalg.pinv(mat1)}")
print(f"The kronecker product of mat is {np.kron(mat1, mat2)}")  # numpy + 2 args

The inverse of mat is [[-1.5   0.5 ]
 [ 1.25 -0.25]]
The determinant of mat is -4.0
The trace of mat is 7
The vector norm of mat is 8.12403840463596
The pseudo inverse of mat is [[-1.5   0.5 ]
 [ 1.25 -0.25]]
The kronecker product of mat is [[ 56   9   8   4 112  18  16   8]
 [  5   6   7   8  10  12  14  16]
 [280  45  40  20 336  54  48  24]
 [ 25  30  35  40  30  36  42  48]]


# Matrix Decomposition
It means breaking the matrix into simpler parts

In [14]:
# LU Decomposition (mat1)
P, L, U = linalg.lu(mat1)
print("LU Decomposition of mat1:")
print(f"P (Permutation):\n{P}")
print(f"L (Lower):\n{L}")
print(f"U (Upper):\n{U}")
print(f"Verification P @ L @ U:\n{P @ L @ U}")  # Should equal mat1


LU Decomposition of mat1:
P (Permutation):
[[0. 1.]
 [1. 0.]]
L (Lower):
[[1.  0. ]
 [0.2 1. ]]
U (Upper):
[[5.  6. ]
 [0.  0.8]]
Verification P @ L @ U:
[[1. 2.]
 [5. 6.]]


In [15]:
# QR Decomposition (mat1)
Q, R = linalg.qr(mat1)
print("\nQR Decomposition of mat1:")
print(f"Q (Orthogonal):\n{Q}")
print(f"R (Upper Triangular):\n{R}")
print(f"Verification Q @ R:\n{Q @ R}")  # Should equal mat1


QR Decomposition of mat1:
Q (Orthogonal):
[[-0.19611614 -0.98058068]
 [-0.98058068  0.19611614]]
R (Upper Triangular):
[[-5.09901951 -6.27571632]
 [ 0.         -0.78446454]]
Verification Q @ R:
[[1. 2.]
 [5. 6.]]


In [16]:
# SVD (mat1)
U, S, Vh = linalg.svd(mat1)
print("\nSVD of mat1:")
print(f"U:\n{U}")
print(f"S (Singular Values):\n{S}")
print(f"Vh:\n{Vh}")


SVD of mat1:
U:
[[-0.26945546 -0.96301285]
 [-0.96301285  0.26945546]]
S (Singular Values):
[8.10904919 0.49327608]
Vh:
[[-0.62701799 -0.77900477]
 [ 0.77900477 -0.62701799]]


In [17]:
# Eigenvalue Decomposition (mat1 only - must be square)
eigenvalues, eigenvectors = linalg.eig(mat1)
print("\nEigenvalue Decomposition of mat1:")
print(f"Eigenvalues:\n{eigenvalues}")
print(f"Eigenvectors:\n{eigenvectors}")


Eigenvalue Decomposition of mat1:
Eigenvalues:
[-0.53112887+0.j  7.53112887+0.j]
Eigenvectors:
[[-0.79402877 -0.2928046 ]
 [ 0.60788018 -0.9561723 ]]


In [18]:
# Make mat1 positive definite first
mat1_pd = mat1.T @ mat1  # A^T * A is always positive definite

L = linalg.cholesky(mat1_pd, lower=True)
print("\nCholesky Decomposition of mat1^T @ mat1:")
print(f"L (Lower Triangular):\n{L}")
print(f"Verification L @ L.T:\n{L @ L.T}")  # Should equal mat1_pd


Cholesky Decomposition of mat1^T @ mat1:
L (Lower Triangular):
[[5.09901951 0.        ]
 [6.27571632 0.78446454]]
Verification L @ L.T:
[[26. 32.]
 [32. 40.]]
