In [1]:
import numpy as np 
from scipy import linalg

# Linear Algebra

The scipy.linalg() provides fas , stable & feature rich linear algebra routines . This module is build on top of optimized lib .

In [10]:
# The numpy matrix
mat1 = np.array([[1,2,] , [5,6]])
print(mat1)

mat2 = np.array([[56,9,8,4] , [5,6,7,8] , [3,4,5,6] , [45,34,54,56]])
print(mat2)

[[1 2]
 [5 6]]
[[56  9  8  4]
 [ 5  6  7  8]
 [ 3  4  5  6]
 [45 34 54 56]]


# Basic Matrix Operations

In [11]:
print(f"The inverse of mat is {linalg.inv(mat1)}")
print(f"The determinant of mat is {linalg.det(mat1)}")
print(f"The trace of mat is {np.trace(mat1)}")              # numpy, not linalg
print(f"The vector norm of mat is {linalg.norm(mat1)}")
print(f"The pseudo inverse of mat is {linalg.pinv(mat1)}")
print(f"The kronecker product of mat is {np.kron(mat1, mat2)}")  # numpy + 2 args

The inverse of mat is [[-1.5   0.5 ]
 [ 1.25 -0.25]]
The determinant of mat is -4.0
The trace of mat is 7
The vector norm of mat is 8.12403840463596
The pseudo inverse of mat is [[-1.5   0.5 ]
 [ 1.25 -0.25]]
The kronecker product of mat is [[ 56   9   8   4 112  18  16   8]
 [  5   6   7   8  10  12  14  16]
 [  3   4   5   6   6   8  10  12]
 [ 45  34  54  56  90  68 108 112]
 [280  45  40  20 336  54  48  24]
 [ 25  30  35  40  30  36  42  48]
 [ 15  20  25  30  18  24  30  36]
 [225 170 270 280 270 204 324 336]]


# Matrix Decomposition
It means breaking the matrix into simpler parts

In [12]:
# LU Decomposition (mat1)
P, L, U = linalg.lu(mat1)
print("LU Decomposition of mat1:")
print(f"P (Permutation):\n{P}")
print(f"L (Lower):\n{L}")
print(f"U (Upper):\n{U}")
print(f"Verification P @ L @ U:\n{P @ L @ U}")  # Should equal mat1


LU Decomposition of mat1:
P (Permutation):
[[0. 1.]
 [1. 0.]]
L (Lower):
[[1.  0. ]
 [0.2 1. ]]
U (Upper):
[[5.  6. ]
 [0.  0.8]]
Verification P @ L @ U:
[[1. 2.]
 [5. 6.]]


In [15]:
# QR Decomposition (mat1)
Q, R = linalg.qr(mat1)
print("\nQR Decomposition of mat1:")
print(f"Q (Orthogonal):\n{Q}")
print(f"R (Upper Triangular):\n{R}")
print(f"Verification Q @ R:\n{Q @ R}")  # Should equal mat1


QR Decomposition of mat1:
Q (Orthogonal):
[[-0.19611614 -0.98058068]
 [-0.98058068  0.19611614]]
R (Upper Triangular):
[[-5.09901951 -6.27571632]
 [ 0.         -0.78446454]]
Verification Q @ R:
[[1. 2.]
 [5. 6.]]


In [13]:
# SVD (mat1)
U, S, Vh = linalg.svd(mat1)
print("\nSVD of mat1:")
print(f"U:\n{U}")
print(f"S (Singular Values):\n{S}")
print(f"Vh:\n{Vh}")


SVD of mat1:
U:
[[-0.26945546 -0.96301285]
 [-0.96301285  0.26945546]]
S (Singular Values):
[8.10904919 0.49327608]
Vh:
[[-0.62701799 -0.77900477]
 [ 0.77900477 -0.62701799]]


In [17]:
# Eigenvalue Decomposition (mat1 only - must be square)
eigenvalues, eigenvectors = linalg.eig(mat1)
print("\nEigenvalue Decomposition of mat1:")
print(f"Eigenvalues:\n{eigenvalues}")
print(f"Eigenvectors:\n{eigenvectors}")


Eigenvalue Decomposition of mat1:
Eigenvalues:
[-0.53112887+0.j  7.53112887+0.j]
Eigenvectors:
[[-0.79402877 -0.2928046 ]
 [ 0.60788018 -0.9561723 ]]


In [14]:
# Make mat1 positive definite first
mat1_pd = mat1.T @ mat1  # A^T * A is always positive definite

L = linalg.cholesky(mat1_pd, lower=True)
print("\nCholesky Decomposition of mat1^T @ mat1:")
print(f"L (Lower Triangular):\n{L}")
print(f"Verification L @ L.T:\n{L @ L.T}")  # Should equal mat1_pd


Cholesky Decomposition of mat1^T @ mat1:
L (Lower Triangular):
[[5.09901951 0.        ]
 [6.27571632 0.78446454]]
Verification L @ L.T:
[[26. 32.]
 [32. 40.]]


# Eigen value problems

In [15]:
print(f"The eigen + values values of mat1 is {linalg.eig(mat1)}")
print(f"The values for symmetric mat is {linalg.eigh(mat1)}")
print(f"only eigen values {linalg.eigvals(mat1)}")
print(linalg.eig_banded)

The eigen + values values of mat1 is (array([-0.53112887+0.j,  7.53112887+0.j]), array([[-0.79402877, -0.2928046 ],
       [ 0.60788018, -0.9561723 ]]))
The values for symmetric mat is (array([-2.09016994,  9.09016994]), array([[-0.85065081,  0.52573111],
       [ 0.52573111,  0.85065081]]))
only eigen values [-0.53112887+0.j  7.53112887+0.j]
<function eig_banded at 0x0000019BFEA63380>


# Matrix Functions

In [16]:
print(f"The mat expo {linalg.expm(mat1)}")
print(f"The mat log {linalg.logm(mat1)}")
print(f"The sq root of mat {linalg.sqrtm(mat1)}")
print(f"mat cosin {linalg.cosm(mat1)}")
print(f"mat sin {linalg.sinm(mat1)}")

The mat expo [[ 354.70419645  462.5557803 ]
 [1156.38945076 1511.09364721]]
The mat log [[-0.12913971+2.54496285j  0.65782951-0.77933322j]
 [ 1.64457378-1.94833305j  1.51543407+0.5966298j ]]
The sq root of mat [[0.52117684+0.59037986j 0.68077462-0.18078953j]
 [1.70193655-0.45197382j 2.22311339+0.13840603j]]
mat cosin [[ 0.75874026 -0.13518859]
 [-0.33797147  0.42076879]]
mat sin [[-0.23021353  0.36090168]
 [ 0.90225421  0.67204068]]


# Special Matrices

In [22]:
print(linalg.toeplitz(mat1 , mat2))

[[ 1  9  8  4  5  6  7  8  3  4  5  6 45 34 54 56]
 [ 2  1  9  8  4  5  6  7  8  3  4  5  6 45 34 54]
 [ 5  2  1  9  8  4  5  6  7  8  3  4  5  6 45 34]
 [ 6  5  2  1  9  8  4  5  6  7  8  3  4  5  6 45]]


C:\Users\SANJAY LADE\AppData\Local\Temp\ipykernel_16924\1597252792.py:1: FutureWarning: Beginning in SciPy 1.17, multidimensional input will be treated as a batch, not `ravel`ed. To preserve the existing behavior and silence this warning, `ravel` arguments before passing them to `toeplitz`.
  print(linalg.toeplitz(mat1 , mat2))
