In [7]:
import numpy as np 
from scipy import linalg

# Linear Algebra

The scipy.linalg() provides fas , stable & feature rich linear algebra routines . This module is build on top of optimized lib .

In [10]:
# The numpy matrix
mat1 = np.array([[1,2,] , [5,6]])
print(mat1)

mat2 = np.array([[56,9,8,4] , [5,6,7,8]])
print(mat2)


[[1 2]
 [5 6]]
[[56  9  8  4]
 [ 5  6  7  8]]


# Basic Matrix Operations

In [12]:
print(f"The inverse of mat is {linalg.inv(mat1)}")
print(f"The determinant of mat is {linalg.det(mat1)}")
print(f"The trace of mat is {np.trace(mat1)}")              # numpy, not linalg
print(f"The vector norm of mat is {linalg.norm(mat1)}")
print(f"The pseudo inverse of mat is {linalg.pinv(mat1)}")
print(f"The kronecker product of mat is {np.kron(mat1, mat2)}")  # numpy + 2 args

The inverse of mat is [[-1.5   0.5 ]
 [ 1.25 -0.25]]
The determinant of mat is -4.0
The trace of mat is 7
The vector norm of mat is 8.12403840463596
The pseudo inverse of mat is [[-1.5   0.5 ]
 [ 1.25 -0.25]]
The kronecker product of mat is [[ 56   9   8   4 112  18  16   8]
 [  5   6   7   8  10  12  14  16]
 [280  45  40  20 336  54  48  24]
 [ 25  30  35  40  30  36  42  48]]
